export default [
  {
    id: "1",
    title: "Channels",
    subTitle: "See your favorite channels!",
    info1: "Subscribe to different channels to get good feeds",
    nav: "Channel",
    bg: "#ffafbd",
    bg1: "#ffc3a0",
    icon: "tv",
    iconPack: "I",
  },
  {
    id: "48d",
    title: "Stories",
    subTitle: "Daily feeds!",
    info1: "Have fun with watching stories",
    nav: "modal",
    bg: "#42275a",
    bg1: "#734b6d",
    icon: "circle",
    iconPack: "F",
  },
  {
    id: "4",
    title: "Connect",
    subTitle: "Connect with weebos nearby.",
    info1: "Browse and follow your favorite groups",
    nav: "Connect",
    bg: "#36d1dc",
    bg1: "#5b86e5",
    icon: "locate-sharp",
    iconPack: "I",
  },
  {
    id: "2",
    title: "Shows",
    subTitle: "See your favorite anime shows!",
    info1: "Browse and follow your favorite shows",
    nav: "Shows",
    bg: "#2b5876",
    bg1: "#4e4376",
    icon: "tv-sharp",
    iconPack: "I",
  },
  {
    id: "3",
    title: "Groups",
    subTitle: "See anime organizations!",
    info1: "Browse and follow your favorite groups",
    nav: "Group",
    bg: "#06beb6",
    bg1: "#48b1bf",
    icon: "people",
    iconPack: "I",
  },
];
