// export const userPostsApi = [
//   {
//     id: "1",
//     userId: 1,
//     posts: [
//       { postId: "1233", post: require("../assets/cart4.jpg") },
//       { postId: "5389", post: require("../assets/cart5.jpg") },
//       { postId: "3853", post: require("../assets/cart6.jpg") },
//       { postId: "676", post: require("../assets/cart7.jpg") },
//       { postId: "5654", post: require("../assets/cart8.jpg") },
//     ],
//   },
//   {
//     id: 2,
//     userId: 2,
//     posts: [
//       { postId: "7r6", post: require("../assets/cart9.jpg") },
//       { postId: "ytfty", post: require("../assets/cart10.jpg") },
//       { postId: "f865", post: require("../assets/cane6.jpg") },
//       { postId: "8dtc", post: require("../assets/cane5.jpg") },
//       { postId: "86f87", post: require("../assets/cane8.jpg") },
//     ],
//   },
// ];

// export const shoesApi = [
//   { id: "1", image: require("../assets/s1.jpg") },
//   { id: "2", image: require("../assets/s2.jpg") },
//   { id: "3", image: require("../assets/s3.jpg") },
//   { id: "4", image: require("../assets/s4.jpg") },
//   { id: "5", image: require("../assets/s5.jpg") },
//   { id: "6", image: require("../assets/s6.jpg") },
//   { id: "7", image: require("../assets/s7.jpg") },
//   { id: "8", image: require("../assets/s8.jpg") },
//   { id: "9", image: require("../assets/s9.jpg") },
//   { id: "10", image: require("../assets/s10.jpg") },
//   { id: "11", image: require("../assets/s11.jpg") },
//   { id: "12", image: require("../assets/s12.jpg") },
//   { id: "13", image: require("../assets/s13.jpg") },
//   { id: "14", image: require("../assets/s14.jpg") },
//   { id: "15", image: require("../assets/s15.jpg") },
//   { id: "16", image: require("../assets/s16.jpg") },
// ];

// const userMessagesApi = [];

// export const usersApi = [
//   {
//     id: 1,
//     user_name: "Dhannyphantom",
//     first_name: "Daniel",
//     last_name: "Olojo",
//     full_name: function () {
//       return this.first_name + " " + this.last_name;
//     },
//     avatar: require("../assets/cane7.jpg"),
//     characters_owned: [],
//     characters_count: function () {
//       return this.characters_owned.length;
//     },
//     characters_followed: 230,
//     followers: "239M",
//     posts_count: 163,
//     favourite_characters: [
//       { fav_number: 1, character: "Kakashi" },
//       { fav_number: 2, character: "Ban" },
//     ],
//     email: "youngskillzzz@gmail.com",
//     gender: "male",
//     country: "Nigeria",
//     city: "Kabba",
//     post_uploaded: userPostsApi[0],
//     messages: userMessagesApi[0],
//   },
//   {
//     id: 2,
//     user_name: "Hazzazy",
//     first_name: "Temitope",
//     last_name: "Hassan",
//     full_name: function () {
//       return this.first_name + " " + this.last_name;
//     },
//     avatar: require("../assets/cart3.jpg"),
//     characters_Owned: 426,
//     characters_Followed: 193,
//     followers: "469K",
//     posts_count: 459,
//     favourite_characters: [
//       { fav_number: 1, character: "Jiraiya" },
//       { fav_number: 2, character: "Tsunade" },
//     ],
//     email: "Hassantemi@gmail.com",
//     gender: "male",
//     country: "Nigeria",
//     city: "Abuja",
//     post_uploaded: userPostsApi[1],
//     messages: userMessagesApi[1],
//   },
//   {
//     id: 3,
//     user_name: "Dextrous_city",
//     first_name: "Dominic",
//     last_name: "Gbemileke",
//     full_name: function () {
//       return this.first_name + " " + this.last_name;
//     },
//     avatar: require("../assets/cart8.jpg"),
//     characters_Owned: 783,
//     characters_Followed: 370,
//     followers: "7M",
//     posts_count: 853,
//     favourite_characters: [
//       { fav_number: 1, character: "Naruto" },
//       { fav_number: 2, character: "Saitama" },
//     ],
//     email: "dominicdexter@gmail.com",
//     gender: "male",
//     country: "Nigeria",
//     city: "Abuja",
//     post_uploaded: userPostsApi[2],
//     messages: userMessagesApi[2],
//   },
// ];

// export const characterApi = [
//   // {
//   //   id: 1,
//   //   name: "Ban",
//   //   show: "Seven Deadly Sins",
//   //   followers: 3824,
//   //   avatar: usersApi[0].avatar,
//   //   cover_photo: require("../assets/cane7.jpg"),
//   //   owner: "Dhannyphantom",
//   //   creator: "Dextrous_city",
//   // },
//   // {
//   //   id: 2,
//   //   name: "Meliodas",
//   //   show: "Seven Deadly Sins",
//   //   followers: 374,
//   //   avatar: usersApi[0].avatar,
//   //   cover_photo: require("../assets/cane5.jpg"),
//   //   owner: "Dhannyphantom",
//   //   creator: "Dextrous_city",
//   // },
//   {
//     id: 3,
//     name: "Mori",
//     show: "God of High School",
//     followers: 78589384395,
//     avatar: usersApi[0].avatar,
//     cover_photo: require("../assets/cane6.jpg"),
//     owner: "Dhannyphantom",
//     creator: "Dextrous_city",
//   },
//   {
//     id: 4,
//     name: "Kibetsu",
//     show: "Demon Slayer",
//     followers: 5748359,
//     avatar: usersApi[1].avatar,
//     cover_photo: require("../assets/cart4.jpg"),
//     owner: "Hazzazy",
//     creator: "Dextrous_city",
//   },
//   {
//     id: 5,
//     name: "Daewi",
//     show: "God of High School",
//     followers: 753834,
//     avatar: usersApi[1].avatar,
//     cover_photo: require("../assets/cart5.jpg"),
//     owner: "Hazzazy",
//     creator: "Dextrous_city",
//   },
//   {
//     id: 6,
//     name: "Zenitsu",
//     show: "Demon Slayer",
//     followers: 12438,
//     avatar: usersApi[1].avatar,
//     cover_photo: require("../assets/cart6.jpg"),
//     owner: "Hazzazy",
//     creator: "Dextrous_city",
//   },
//   {
//     id: 7,
//     name: "Escanor",
//     show: "Seven Deadly Sins",
//     followers: 33737539,
//     avatar: usersApi[2].avatar,
//     cover_photo: require("../assets/hulk.jpg"),
//     owner: "Dextrous_city",
//     creator: "Dhannyphantom",
//   },
//   {
//     id: 8,
//     name: "Gowther",
//     show: "Seven Deadly Sins",
//     followers: 2485380,
//     avatar: usersApi[1].avatar,
//     cover_photo: require("../assets/cart8.jpg"),
//     owner: "Hazzazy",
//     creator: "Dhannyphantom",
//   },
//   {
//     id: 9,
//     name: "Sinosuke",
//     show: "Demon Slayer",
//     followers: 304040,
//     avatar: usersApi[2].avatar,
//     cover_photo: require("../assets/cart9.jpg"),
//     owner: "Dextrous_city",
//     creator: "Hazzazy",
//   },
//   {
//     id: 10,
//     name: "Nezuko",
//     show: "Demon Slayer",
//     followers: 4737493,
//     avatar: usersApi[2].avatar,
//     cover_photo: require("../assets/naru.jpg"),
//     owner: "Dextrous_city",
//     creator: "Hazzzazy",
//   },
// ];

// export const challengeApi = [
//   {
//     id: 1,
//     character: "Naruto",
//     countdown: "14 hrs",
//     avatar1: usersApi[0].avatar,
//     avatar2: usersApi[1].avatar,
//     name1: "Dhannyphantom",
//     name2: "Hazzazy",
//     challenge1: require("../assets/cane5.jpg"),
//     challenge2: require("../assets/cane7.jpg"),
//     score1: 2429,
//     score2: 7651,
//     comments: [],
//   },
//   {
//     id: 2,
//     character: "Luffy",
//     countdown: "12 hrs",
//     avatar1: usersApi[0].avatar,
//     avatar2: usersApi[2].avatar,
//     name1: "Dhannyphantom",
//     name2: "Dextrous_city",
//     challenge1: require("../assets/cart5.jpg"),
//     challenge2: require("../assets/cart6.jpg"),
//     score1: 87675,
//     score2: 1435,
//     comments: [],
//   },
//   {
//     id: 3,
//     character: "Luffy",
//     countdown: "12 hrs",
//     avatar1: usersApi[1].avatar,
//     avatar2: usersApi[2].avatar,
//     name1: "Hazzazy",
//     name2: "Dextrous_city",
//     challenge1: require("../assets/cart7.jpg"),
//     challenge2: require("../assets/cart8.jpg"),
//     score1: 5250,
//     score2: 5250,
//     comments: [],
//   },
// ];

// export const alertApi = [
//   {
//     id: "1",
//     name: "Hazzazy",
//     avatar: require("../assets/cane7.jpg"),
//     character: "Ban",
//     date: "12th Nov,19999",
//     active: true,
//     system: false,
//     message: "",
//   },
//   {
//     id: "2",
//     name: "Dexter",
//     avatar: require("../assets/cane8.jpg"),
//     character: "Gon",
//     date: "13th Nov,19999",
//     active: false,
//     system: false,
//     message: "",
//   },
//   {
//     id: "3",
//     name: "SholaTy",
//     avatar: require("../assets/cart3.jpg"),
//     character: "Killua",
//     date: "12th Aug,1999",
//     active: false,
//     system: false,
//     message: "",
//   },
//   {
//     id: "4",
//     name: "Laycon",
//     avatar: require("../assets/cane5.jpg"),
//     character: "Mori",
//     date: "2th Nov,19999",
//     active: true,
//     system: false,
//     message: "",
//   },
//   {
//     id: "5",
//     name: "Owen",
//     avatar: require("../assets/cane9.jpg"),
//     character: "Saitama",
//     date: "12th Nov,19999",
//     active: true,
//     system: false,
//     message: "",
//   },
//   {
//     id: "6",
//     name: "",
//     avatar: null,
//     character: "",
//     date: "12th Nov,19999",
//     active: true,
//     system: true,
//     message: "You're losing your Ban Character",
//   },
//   {
//     id: "7",
//     name: "Rebeccca",
//     avatar: require("../assets/cart4.jpg"),
//     character: "Daewi",
//     date: "11th Nov,2000",
//     active: false,
//     system: false,
//     message: "",
//   },
//   {
//     id: "8",
//     name: "Junior",
//     avatar: require("../assets/cart7.jpg"),
//     character: "Naruto",
//     date: "12th Nov,2020",
//     active: true,
//     system: false,
//     message: "",
//   },
//   {
//     id: "9",
//     name: "",
//     avatar: null,
//     character: "",
//     date: "12th Nov,2020",
//     active: true,
//     system: true,
//     message: "You lost your Kakashi Character",
//   },
//   {
//     id: "10",
//     name: "",
//     avatar: null,
//     character: "",
//     date: "12th Nov,2020",
//     active: false,
//     system: true,
//     message: "Your Kakashi character is inivited to a challenge",
//   },
//   {
//     id: "11",
//     name: "",
//     avatar: null,
//     character: "",
//     date: "12th Nov,2020",
//     active: true,
//     system: true,
//     message: "Your Kakashi character won the Most Coolest Character challenge",
//   },
// ];

// export const awardsApi = [
//   {
//     id: "1",
//     awardType: "Most Perverted Character",
//     character: characterApi[0],
//   },
//   { id: "1", awardType: "Most Coolest Character", character: characterApi[1] },
//   { id: "1", awardType: "Most Bad Ass Character", character: characterApi[2] },
//   { id: "1", awardType: "Most Dreadful Character", character: characterApi[3] },
//   {
//     id: "1",
//     awardType: "Most Strongest Character",
//     character: characterApi[4],
//   },
// ];

export const dummy = [
  {
    id: "1",
    text: "A",
  },
  {
    id: "2",
    text: "B",
  },
  {
    id: "3",
    text: "C",
  },
  {
    id: "4",
    text: "D",
  },
  {
    id: "5",
    text: "FF",
  },
  {
    id: "31",
    text: "FWA",
  },
  {
    id: "41",
    text: "FEA",
  },
  {
    id: "1353",
    text: "RAFEE",
  },
  {
    id: "15332",
    text: "AFEGE",
  },
  {
    id: "15323",
    text: "AFEWE",
  },
  {
    id: "15343",
    text: "AFERGEE",
  },
  {
    id: "15353",
    text: "AFEEFE",
  },
  {
    id: "15326",
    text: "AFEEFGE",
  },
  {
    id: "15354",
    text: "AFFVSDEE",
  },
  {
    id: "156323",
    text: "AFEFEDGE",
  },
  {
    id: "1538765",
    text: "AFEESBFGF",
  },
  {
    id: "157563",
    text: "AFESDFGHE",
  },
  {
    id: "158653",
    text: "AFESFGDHFE",
  },
  {
    id: "15386544",
    text: "AFEESDGHJ",
  },
  {
    id: "1538564",
    text: "AFESDGHJGE",
  },
  {
    id: "158765433",
    text: "AFEESDGHF",
  },
  {
    id: "2356153",
    text: "AFWSDGFHEE",
  },
];
